FROM bioinfoufsc/proteomic-interpro:latest

RUN apt-get update -y \
    && apt-get install --no-install-recommends -y \
    apt-utils \
    maven \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# python libraries
WORKDIR /
ARG CACHE_BUST=$(date +%s)
RUN git clone https://github.com/bioinformatics-ufsc/FastProtein.git
WORKDIR /FastProtein
RUN pip3 install --no-cache-dir -r requirements.txt

# Criando diretório bioinformatic e copiando arquivosRUN mkdir temp
RUN mkdir /FastProtein/temp

# set environment variables
ENV FASTPROTEIN_HOME="/FastProtein" \
    DATABASE_HOME="/FastProtein/db" \
    FLASK_RUN_HOST="0.0.0.0" \
    FLASK_DEBUG="False" \
    FLASK_HOME="/FastProtein/web" \
    FLASK_APP="/FastProtein/web/server.py" \
    FLASK_REMOVE_RESULT_DIR="Yes"

RUN chmod +x /FastProtein/bin/*.sh /FastProtein/web/server.sh \
    && ln -s /FastProtein/bin/fastprotein.sh /usr/local/bin/fastprotein \
    && ln -s /FastProtein/web/server.sh /usr/local/bin/server \
    && echo "source server" >> ~/.bashrc

# build fastprotein
RUN mvn -f /FastProtein/pom.xml clean install

# required directory for runs
RUN mkdir -p /FastProtein/runs

# expose the application port
EXPOSE 5000

# set volume for fastprotein runs and working directory
VOLUME /FastProtein/runs
WORKDIR /FastProtein

