#CONTAINS INTERPROSCAN
FROM bioinfoufsc/proteomic:clean-latest

RUN apt-get update -y \
    && apt-get install --no-install-recommends -y \
    aria2 \
    pigz \
    openjdk-17-jdk \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN aria2c --continue=true --max-connection-per-server=8 --min-split-size=2M -d /bioinformatic https://ftp.ebi.ac.uk/pub/software/unix/iprscan/5/5.69-101.0/interproscan-5.69-101.0-64-bit.tar.gz
RUN tar --use-compress-program=pigz -xvf /bioinformatic/interproscan-5.69-101.0-64-bit.tar.gz -C /bioinformatic

ENV INTERPRO_HOME="/bioinformatic/interproscan-5.69-101.0"
WORKDIR $INTERPRO_HOME
RUN ln -sf $INTERPRO_HOME/interproscan.sh  /usr/local/bin/interproscan
RUN python3 setup.py -f interproscan.properties
RUN echo "InterProScan installed successfuly at $INTERPRO_HOME"
WORKDIR /data


